services:
  api:
    build: .
    container_name: pet-api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql+asyncpg://pet:pet@db:5432/petdb"

  db:
    image: postgres:15
    container_name: pet-db
    restart: always
    environment:
      POSTGRES_USER: pet
      POSTGRES_PASSWORD: pet
      POSTGRES_DB: petdb
    ports:
      - "5432:5432"
    volumes:
      - pet-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pet-data:
